version: '3.4'

networks:
    assignment1-network:
        external: true

services:            
  dotnet-csharp-react_energyapp_ds:
    image: ${DOCKER_REGISTRY-}dotnetcsharpreactenergyappds
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
        bash -c "dotnet ef migrations add FirstMigration
        && dotnet ef database update
        && dotnet run /Users/acsatlos/Projects/UTCN-DS-Project/dotnet-backend/DotNet-CSharp-React_EnergyApp_DS"
    volumes:
      - .:/code
    ports:
      - "5024:5024"
      - "5025:5025"
    environment:
      - POSTGRES_DB=devicemanager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=postgres-integration
      - POSTGRES_PORT=5432
      - ASPNETCORE_HTTP_PORT=https://+:5025
      - ASPNETCORE_URLS=http://+:5024
    depends_on:
      - postgres-integration
    networks:
        assignment1-network:
            ipv4_address: 172.16.0.53
